/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionEvent;

/**
 *
 * @author Ricardo
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    public Dashboard(String dashboard) {
       initComponents();
       this.setTitle(dashboard);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarDashboard = new javax.swing.JMenuBar();
        jMenuAgregar = new javax.swing.JMenu();
        jMenuEditar = new javax.swing.JMenu();
        jMenuEliminar = new javax.swing.JMenu();
        jMenuActulizar = new javax.swing.JMenu();
        jMenuActuliar = new javax.swing.JMenu();
        jMenuItemActulizarTop100 = new javax.swing.JMenuItem();
        jMenuItemActulizarTop1000 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jframeDashboard"); // NOI18N
        setUndecorated(true);

        jMenuAgregar.setText("Agregar");
        jMenuAgregar.setToolTipText("");
        jMenuBarDashboard.add(jMenuAgregar);

        jMenuEditar.setText("Editar");
        jMenuBarDashboard.add(jMenuEditar);

        jMenuEliminar.setText("Eliminar");
        jMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarActionPerformed(evt);
            }
        });
        jMenuBarDashboard.add(jMenuEliminar);

        jMenuActulizar.setText("Actulizar");

        jMenuActuliar.setText("Rangos actualización");
        jMenuActuliar.setToolTipText("");

        jMenuItemActulizarTop100.setText("Primeros 100");
        jMenuItemActulizarTop100.setName(""); // NOI18N
        jMenuItemActulizarTop100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActulizarTop100ActionPerformed(evt);
            }
        });
        jMenuActuliar.add(jMenuItemActulizarTop100);

        jMenuItemActulizarTop1000.setLabel("Primeros 1000");
        jMenuActuliar.add(jMenuItemActulizarTop1000);
        jMenuItemActulizarTop1000.getAccessibleContext().setAccessibleName("");

        jMenuActulizar.add(jMenuActuliar);

        jMenuBarDashboard.add(jMenuActulizar);

        setJMenuBar(jMenuBarDashboard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemActulizarTop100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActulizarTop100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemActulizarTop100ActionPerformed

    private void jMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuActuliar;
    private javax.swing.JMenu jMenuActulizar;
    private javax.swing.JMenu jMenuAgregar;
    private javax.swing.JMenuBar jMenuBarDashboard;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuEliminar;
    private javax.swing.JMenuItem jMenuItemActulizarTop100;
    private javax.swing.JMenuItem jMenuItemActulizarTop1000;
    // End of variables declaration//GEN-END:variables
}
